10:03:56.073 Running build in Washington, D.C., USA (East) – iad1
10:03:56.074 Build machine configuration: 2 cores, 8 GB
10:03:56.088 Cloning github.com/odairorso/Estetica-Rosana (Branch: main, Commit: bbf62c0)
10:03:56.409 Cloning completed: 320.000ms
10:03:57.214 Restored build cache from previous deployment (6AnG3kL4r7NjwSUQm7rbbiMSpLic)
10:03:57.830 Running "vercel build"
10:03:58.217 Vercel CLI 48.0.2
10:03:59.263 Error while parsing config file: "/vercel/path0/package-lock.json"
10:03:59.340 Error while parsing config file: "/vercel/path0/package-lock.json"
10:03:59.361 Detected `pnpm-lock.yaml` 9 which may be generated by pnpm@9.x or pnpm@10.x
10:03:59.362 Using pnpm@10.x based on project creation date
10:03:59.362 To use pnpm@9.x, manually opt in using corepack (https://vercel.com/docs/deployments/configure-a-build#corepack)
10:03:59.363 Running "install" command: `npm install`...
10:04:01.136 
10:04:01.137 added 1 package, and audited 400 packages in 2s
10:04:01.138 
10:04:01.138 79 packages are looking for funding
10:04:01.138   run `npm fund` for details
10:04:01.145 
10:04:01.146 2 moderate severity vulnerabilities
10:04:01.146 
10:04:01.146 To address all issues, run:
10:04:01.146   npm audit fix
10:04:01.146 
10:04:01.146 Run `npm audit` for details.
10:04:01.392 
10:04:01.392 > estetica-rosana@0.0.0 build
10:04:01.393 > vite build
10:04:01.394 
10:04:01.819 [36mvite v5.4.19 [32mbuilding for production...[36m[39m
10:04:01.875 transforming...
10:04:03.840 [32m✓[39m 56 modules transformed.
10:04:03.841 [31mx[39m Build failed in 2.00s
10:04:03.842 [31merror during build:
10:04:03.842 [31m[vite:esbuild] Transform failed with 1 error:
10:04:03.842 /vercel/path0/src/components/packages/SessionHistoryModal.tsx:20:0: ERROR: Unexpected "<<"[31m
10:04:03.842 file: [36m/vercel/path0/src/components/packages/SessionHistoryModal.tsx:20:0[31m
10:04:03.842 [33m
10:04:03.842 [33mUnexpected "<<"[33m
10:04:03.842 18 |    if (!pkg) return null;
10:04:03.843 19 |  
10:04:03.843 20 |  <<<<<<< HEAD
10:04:03.843    |  ^
10:04:03.843 21 |  
10:04:03.843 22 |  
10:04:03.843 [31m
10:04:03.843     at failureErrorWithLog (/vercel/path0/node_modules/esbuild/lib/main.js:1472:15)
10:04:03.843     at /vercel/path0/node_modules/esbuild/lib/main.js:755:50
10:04:03.843     at responseCallbacks.<computed> (/vercel/path0/node_modules/esbuild/lib/main.js:622:9)
10:04:03.843     at handleIncomingPacket (/vercel/path0/node_modules/esbuild/lib/main.js:677:12)
10:04:03.844     at Socket.readFromStdout (/vercel/path0/node_modules/esbuild/lib/main.js:600:7)
10:04:03.844     at Socket.emit (node:events:519:28)
10:04:03.844     at addChunk (node:internal/streams/readable:561:12)
10:04:03.844     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
10:04:03.844     at Readable.push (node:internal/streams/readable:392:5)
10:04:03.844     at Pipe.onStreamRead (node:internal/stream_base_commons:189:23)[39m
10:04:03.863 Error: Command "npm run build" exited with 1