CREATE TABLE public.sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  client_id BIGINT REFERENCES public.clients(id) ON DELETE SET NULL,
  client_name TEXT NOT NULL,
  items JSONB NOT NULL,
  total NUMERIC NOT NULL,
  sale_date DATE NOT NULL,
  payment_method TEXT NOT NULL,
  notes TEXT
);

ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.sales
  FOR SELECT USING (TRUE);

CREATE POLICY "Enable insert for authenticated users" ON public.sales
  FOR INSERT TO authenticated WITH CHECK (TRUE);

CREATE POLICY "Enable update for authenticated users" ON public.sales
  FOR UPDATE TO authenticated USING (TRUE) WITH CHECK (TRUE);

CREATE POLICY "Enable delete for authenticated users" ON public.sales
  FOR DELETE TO authenticated USING (TRUE);
